name: Deploy

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production
  REPOSITORY_NAME: IP2GeoVapor
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  SSHKEY: ${{ secrets.SSHKEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ env.SSHKEY }}
        port: ${{ env.PORT }}
        script: |
          whoami
          ls -al
          
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"

    - name: Cache Swift Package Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.swiftpm
        key: ${{ runner.os }}-swift-${{ env.SWIFT_VERSION }}-swiftpm
        restore-keys: |
          ${{ runner.os }}-swift-${{ env.SWIFT_VERSION }}-swiftpm

    - name: Build Vapor API
      run: swift build --configuration release

    - name: Deploy to production
      run: .build/release/Run serve --env ${{env.ENVIRONMENT}} --port 3001 --hostname 127.0.0.1
