name: Deploy

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production
  REPOSITORY_NAME: IP2GeoVapor
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  SSHKEY: ${{ secrets.SSHKEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Vapor API
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ env.SSHKEY }}
        port: ${{ env.PORT }}
        script: |
          cd /root/swift/IP2GeoVapor
          ls
          git pull
          swift build --configuration release
          nohup .build/release/Run serve --env ${{env.ENVIRONMENT}} --port 3001 --hostname 127.0.0.1 &
