name: Deploy

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production
  REPOSITORY_NAME: IP2GeoVapor
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  SSHKEY: ${{ secrets.SSHKEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"

    - name: Build Vapor API
      run: swift build --configuration release

    - name: Deploy to production
      run: |
        mkdir -p /deploy
        cp -r .build/release/RepositoryName /deploy/
        scp -P ${{ env.PORT }} -i ${{ env.SSHKEY }} -r /deploy ${{ env.USERNAME }}@${{ env.HOST }}:/var/www/${{ env.REPOSITORY_NAME }}
        ssh -p ${{ env.PORT }} -i ${{ env.SSHKEY }} ${{ env.USERNAME }}@${{ env.HOST }} "systemctl restart vapor-${{ env.REPOSITORY_NAME }}"
