name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
      
env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  SSHKEY: ${{ secrets.SSHKEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ env.SSHKEY }}
        port: ${{ env.PORT }}
        script: |
          whoami
          cd /root/swift/IP2GeoVapor
          git reset --hard
          git pull --force
          docker build . -t ip2geo-vapor
          docker stop $(docker ps --filter "name=vaporAPI" --format "{{.ID}}") || true
          docker rm $(docker ps -a --filter "name=vaporAPI" --format "{{.ID}}") || true
          docker run -d --name vaporAPI_new -p 3001:3001 ip2geo-vapor
          sleep 10 # wait for the new container to start
          docker ps -f name=vaporAPI_new -q | xargs -I {} docker rename {} vaporAPI
          docker image prune -a --force
