name: test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/Library/Caches/SwiftPM
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    - name: Build
      run: swift build
    - name: Test
      run: swift test
