name: test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Swift on Linux
      uses: sersoft-gmbh/swifty-linux-action@v2.1.1
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
            .build/workspace-state.json
        key: test-spm-${{ runner.os }}-${{ hashFiles('Package.swift', 'Package.resolved') }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
