name: test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Swift
      uses: sersoft-gmbh/swifty-linux-action@v2
      with:
        branch-name: swift-5.7-branch
        version-tag: swift-5.7-DEVELOPMENT-SNAPSHOT-2022-06-13-a
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
            .build/workspace-state.json
        key: test-spm-${{ runner.os }}-${{ hashFiles('Package.swift', 'Package.resolved') }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
