name: test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.4.0
      with:
        version: 5.6
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          .build/artifacts
          .build/checkouts
          .build/repositories
          .build/workspace-state.json
        key: test-spm-${{ runner.os }}-${{ hashFiles('Package.swift', 'Package.resolved') }}
    - name: Build and Test
      run: swift test
